name: Virtool CI

on:
  push:
    branches:
      - test-actions
jobs:
  server:

    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.0
      mongo:
        image: mongo:4.2

    container:
      image: virtool/external-tools:0.1.2

    steps:
      - uses: actions/checkout@v2
#      - name: test
#        run: |
#          pip install -qr requirements.txt
#          pytest  -x --db-connection-string mongodb://mongo:27017 --redis-connection-string redis://redis:6379 --cov --cov-report xml
      - name: check
        run: readlink -f coverage.xml